### PR TITLE
WIP: first demo for generating a Chiral Spin Liquid (CSL) state

### PR DESCRIPTION
**Pull request by JerryChen97**
After checking our demo code, I believe that most of it can be replaced by more compact expressions which have already been implemented by the newest version of `TeNPy`. So I am trying to replace the replaceable parts with the corresponding methods, e.g. the part where we were applying an MPO to an MPS can be replaced by `MPO.apply()`.

### CODE REVIEW

**Comment by JerryChen97** [comment]
BTW the single file in the original repo has been renamed to `*.py` so that the automatical highlights in GitHub work properly.

**Comment by JerryChen97** [comment]
In the recent commit, I established the logic of correctly extracting the ES info (entanglement entropy) from the MPS psi. I have separated `N`, `Sz` and the corresponding ES. If you want to apply some constraints on the requested site and sector, just apply something in the innermost loop like: 
```
if not f(i, N, Sz): continue
```
where `f` should be the condition you want to enforce on the site `i`, number charge `N` and spin charge `Sz`.

**Comment by JerryChen97** [comment]
For `TeNPy` to correctly calculate the momenta, it seems that we need to have an iMPS. But my current code for this job doesn't run properly, especially after applying the projector.

**Review by ruochenma — APPROVED** [review]
Great! These changes are beyond my level, and look good. Whenever introduce a new function, pay attention to the charge, which is fundamentally important for the project.

**Pull request merged**
